// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARpvq7iQe4e22JaFRjvzaIk2-LwjA5jNI',
    appId: '1:770915425309:web:9d59a7e9248cd0466e7af4',
    messagingSenderId: '770915425309',
    projectId: 'helen-darling-app',
    authDomain: 'helen-darling-app.firebaseapp.com',
    storageBucket: 'helen-darling-app.firebasestorage.app',
    measurementId: 'G-4S1DDCHS2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZRjgnn0AZcA-HU3VhWoRA9PYxeHCf4Lo',
    appId: '1:770915425309:android:1f6c068b9db9bd236e7af4',
    messagingSenderId: '770915425309',
    projectId: 'helen-darling-app',
    storageBucket: 'helen-darling-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPQJ9_548QvweFV7CiX96BmY9iBgzGpSo',
    appId: '1:770915425309:ios:1bad790847bb0cb86e7af4',
    messagingSenderId: '770915425309',
    projectId: 'helen-darling-app',
    storageBucket: 'helen-darling-app.firebasestorage.app',
    iosBundleId: 'com.example.helenDarlingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPQJ9_548QvweFV7CiX96BmY9iBgzGpSo',
    appId: '1:770915425309:ios:1bad790847bb0cb86e7af4',
    messagingSenderId: '770915425309',
    projectId: 'helen-darling-app',
    storageBucket: 'helen-darling-app.firebasestorage.app',
    iosBundleId: 'com.example.helenDarlingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARpvq7iQe4e22JaFRjvzaIk2-LwjA5jNI',
    appId: '1:770915425309:web:7b6f1ef5773f3e8e6e7af4',
    messagingSenderId: '770915425309',
    projectId: 'helen-darling-app',
    authDomain: 'helen-darling-app.firebaseapp.com',
    storageBucket: 'helen-darling-app.firebasestorage.app',
    measurementId: 'G-NJD4JQ7JQE',
  );
}
