// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9iE9ovOvUVLLaXlO9qodaDg0BgLqBG7Y',
    appId: '1:1094867403596:web:63f47fb74c7d292e4885e9',
    messagingSenderId: '1094867403596',
    projectId: 'helen-darling-67ce5',
    authDomain: 'helen-darling-67ce5.firebaseapp.com',
    storageBucket: 'helen-darling-67ce5.firebasestorage.app',
    measurementId: 'G-NMBE30B4GS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkKQ4xK7v6EKb7JDVm7OrXZjSz0NlcpL8',
    appId: '1:1094867403596:android:4c9218874bac76bf4885e9',
    messagingSenderId: '1094867403596',
    projectId: 'helen-darling-67ce5',
    storageBucket: 'helen-darling-67ce5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOYOlZaoTsVcm6-tn-27dHjHVfiqxVZHQ',
    appId: '1:1094867403596:ios:50e897f87ae465784885e9',
    messagingSenderId: '1094867403596',
    projectId: 'helen-darling-67ce5',
    storageBucket: 'helen-darling-67ce5.firebasestorage.app',
    iosBundleId: 'com.example.helenDarlingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOYOlZaoTsVcm6-tn-27dHjHVfiqxVZHQ',
    appId: '1:1094867403596:ios:50e897f87ae465784885e9',
    messagingSenderId: '1094867403596',
    projectId: 'helen-darling-67ce5',
    storageBucket: 'helen-darling-67ce5.firebasestorage.app',
    iosBundleId: 'com.example.helenDarlingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9iE9ovOvUVLLaXlO9qodaDg0BgLqBG7Y',
    appId: '1:1094867403596:web:fbb2b439f23ab22a4885e9',
    messagingSenderId: '1094867403596',
    projectId: 'helen-darling-67ce5',
    authDomain: 'helen-darling-67ce5.firebaseapp.com',
    storageBucket: 'helen-darling-67ce5.firebasestorage.app',
    measurementId: 'G-C53CW20GT6',
  );

}