// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOgBfsJBa1cBesCyYPuAPLKITHJmTsjc8',
    appId: '1:1063341631018:web:0ec0cc2d3a582e63d54553',
    messagingSenderId: '1063341631018',
    projectId: 'luke-lezon-85e67',
    authDomain: 'luke-lezon-85e67.firebaseapp.com',
    storageBucket: 'luke-lezon-85e67.firebasestorage.app',
    measurementId: 'G-2YGDWX9PP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARwvcIMW9bh5__BpEY-pjjsYa0HlA7pvk',
    appId: '1:1063341631018:android:a56a1d7f053493e5d54553',
    messagingSenderId: '1063341631018',
    projectId: 'luke-lezon-85e67',
    storageBucket: 'luke-lezon-85e67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvRoZo9z2QOOLHf3Yj-Pj5A5bsN8bTRSA',
    appId: '1:1063341631018:ios:cf8b8db0177461bdd54553',
    messagingSenderId: '1063341631018',
    projectId: 'luke-lezon-85e67',
    storageBucket: 'luke-lezon-85e67.firebasestorage.app',
    iosBundleId: 'com.example.lukeLezon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvRoZo9z2QOOLHf3Yj-Pj5A5bsN8bTRSA',
    appId: '1:1063341631018:ios:cf8b8db0177461bdd54553',
    messagingSenderId: '1063341631018',
    projectId: 'luke-lezon-85e67',
    storageBucket: 'luke-lezon-85e67.firebasestorage.app',
    iosBundleId: 'com.example.lukeLezon',
  );
}
