// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDUihOvaSJLM1YC3xLWfpIfQrbdlZnsso',
    appId: '1:521464985669:web:6d8cd626c9a9011e7e4b2c',
    messagingSenderId: '521464985669',
    projectId: 'harold-lefty-williams',
    authDomain: 'harold-lefty-williams.firebaseapp.com',
    storageBucket: 'harold-lefty-williams.firebasestorage.app',
    measurementId: 'G-EHL2DLEGZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx8yEjBRy5n-3d4y_akpV3Xwo0Mmslg5g',
    appId: '1:521464985669:android:d267d8d4cae6b4167e4b2c',
    messagingSenderId: '521464985669',
    projectId: 'harold-lefty-williams',
    storageBucket: 'harold-lefty-williams.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ7jRbeaspojrbUwbdBsk2bVYQd2ng3zE',
    appId: '1:521464985669:ios:8cfaf9cf799652e57e4b2c',
    messagingSenderId: '521464985669',
    projectId: 'harold-lefty-williams',
    storageBucket: 'harold-lefty-williams.firebasestorage.app',
    iosBundleId: 'com.example.haroldLeftyWilliams',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ7jRbeaspojrbUwbdBsk2bVYQd2ng3zE',
    appId: '1:521464985669:ios:8cfaf9cf799652e57e4b2c',
    messagingSenderId: '521464985669',
    projectId: 'harold-lefty-williams',
    storageBucket: 'harold-lefty-williams.firebasestorage.app',
    iosBundleId: 'com.example.haroldLeftyWilliams',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDUihOvaSJLM1YC3xLWfpIfQrbdlZnsso',
    appId: '1:521464985669:web:d98426712b3bfb7a7e4b2c',
    messagingSenderId: '521464985669',
    projectId: 'harold-lefty-williams',
    authDomain: 'harold-lefty-williams.firebaseapp.com',
    storageBucket: 'harold-lefty-williams.firebasestorage.app',
    measurementId: 'G-VHZX52R1C8',
  );
}
